# orkestrate 2 java projects and 1 db server
# docker-compose.yml
version: '3.8'
name: postgresql_local
services:
  db:
    image: postgres
    #running every docker start
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
    ports:
      - '5432:5432'
    volumes:
       - /Users/rayakurayasem/Dejo/my-workspace/database/postgresql/data:/var/lib/postgresql/data
       - /Users/rayakurayasem/Dejo/my-workspace/database/postgresql/backups:/var/backups
  datarepo:
    image: datarepo
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
    ports:
      - '8684:8684'
  discovery:
    image: discovery
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
    ports:
      - '8681:8681'
