version: '3.3'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - spring-cloud-network
    ports:
      - 2181:2181
    volumes: 
      - ${PERSIST_STORAGE_PATH_URL}/data/zookeeper:/var/lib/zookeeper/data
      - ${PERSIST_STORAGE_PATH_URL}/logs/zookeeper:/var/lib/zookeeper/log
  kafka-1:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zookeeper-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://${APPLICATION_SERVERIP}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes: 
      - ${PERSIST_STORAGE_PATH_URL}/data/kafka:/var/lib/kafka/data
    networks:
      - spring-cloud-network
  redis:
    image: redis
    networks:
      - spring-cloud-network
    command: redis-server --requirepass prismalink
    restart: always
    environment:
      - 'REDIS_PASSWORD=prismalink'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/data/redis:/bitnami/redis/data
  postgresql:
    image: bitnami/postgresql:15.4.0
    networks:
      - spring-cloud-network
    volumes:
        - ${PERSIST_STORAGE_PATH_URL}/data/postgresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME_CONNECTION_LIMIT=1500
      - POSTGRESQL_PASSWORD=root123
      - TZ=Asia/Jakarta
    ports:
      - 5432:5432
  discovery-server:
    image: prismalinkdev/discovery-server:master-69724e3
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/discovery-server:/usr/apps/log
    ports:
      - 8485:8080
    environment:
      - SERVER_ENV=${SERVER_ENV}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - EUREKA_ZONE=${EUREKA_ZONE}
      - TZ=${TZ}
  datarepo:
    image: prismalinkdev/datarepo:develop-e7bf86f
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/datarepo:/usr/apps/log
    ports:
      - 8490:8080
    depends_on:
      - discovery-server
      - postgresql
    environment:
      - DB_SSL_CONFIG=
      - EUREKA_ZONE=${EUREKA_ZONE}
      - MBDD_DB_MAX_POOL_SIZE=${MBDD_DB_MAX_POOL_SIZE}
      - MBDD_DB_MDO_DB_MDO_SCHEMA=${MBDD_DB_MDO_DB_MDO_SCHEMA}
      - MBDD_DB_MDO_DB_MDO=${MBDD_DB_MDO_DB_MDO}
      - MBDD_DB_MDO_HOST=${MBDD_DB_MDO_HOST}
      - MBDD_DB_MDO_PASS_MDO=${MBDD_DB_MDO_PASS_MDO}
      - MBDD_DB_MDO_PORT=${MBDD_DB_MDO_PORT}
      - MBDD_DB_MDO_USER_MDO=${MBDD_DB_MDO_USER_MDO}
      - MBDD_DB_PLINK_DB_MDO=${MBDD_DB_PLINK_DB_MDO}
      - MBDD_DB_PLINK_HOST=${MBDD_DB_PLINK_HOST}
      - MBDD_DB_PLINK_PASS_MDO=${MBDD_DB_PLINK_PASS_MDO}
      - MBDD_DB_PLINK_PORT=${MBDD_DB_PLINK_PORT}
      - MBDD_DB_PLINK_USER_MDO=${MBDD_DB_PLINK_USER_MDO}
      - MBDD_EUREKA_SERVER_HOST=${MBDD_EUREKA_SERVER_HOST}
      - MBDD_EUREKA_SERVER_PORT=${MBDD_EUREKA_SERVER_PORT}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - SERVER_ENV=${SERVER_ENV}
      - SERVICE_LOGSTASH_HOST=10.6.6.26:5000
      - SERVICE_NAME=datarepo-service-${APPLICATION_SERVERIP}
      - TZ=${TZ}
  api-gateway:
    image: prismalinkdev/apigw:master-bdb8b39
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/api-gateway:/usr/apps/log
    ports:
      - 8486:8080
    depends_on:
      - discovery-server
      - merchant-notification
      - paymentpage
      - payment
      - mbddprocessor
      - checkstatus
      - datarepo
      - redis
    environment:
      - MBDD_REDIS_PORT=${MBDD_REDIS_PORT}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - TZ=${TZ}
      - MBDD_EUREKA_SERVER_HOST=${MBDD_EUREKA_SERVER_HOST}
      - MBDD_EUREKA_SERVER_PORT=${MBDD_EUREKA_SERVER_PORT}
      - MBDD_REDIS_HOST=${MBDD_REDIS_HOST}
      - MBDD_REDIS_PASSWORD=${MBDD_REDIS_PASSWORD}
      - SERVICE_LOGSTASH_HOST=10.6.6.26:5000
      - SERVICE_NAME=apigw-service-${APPLICATION_SERVERIP}
  callback:
    image: prismalinkdev/callback:master-b87456f
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/callback:/usr/apps/log
    ports:
      - 8498:8080
    depends_on:
      - discovery-server
      - datarepo
    environment:
      - APPLICATION_DATAREPO=${APPLICATION_DATAREPO}
      - APPLICATION_DEFAULT_DATAREPO=${APPLICATION_DEFAULT_DATAREPO}
      - APPLICATION_MYDATAREPO=${APPLICATION_MYDATAREPO}
      - APPLICATION_MYDATAREPOCODE=${APPLICATION_MYDATAREPOCODE}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC_7=${KAFKA_TOPIC_7}
      - KAFKA_TOPIC_8=${KAFKA_TOPIC_8}
      - MBDD_EUREKA_SERVER_HOST=${MBDD_EUREKA_SERVER_HOST}
      - MBDD_EUREKA_SERVER_PORT=${MBDD_EUREKA_SERVER_PORT}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - QRIS_NOBU_API_INQUIRY_URL=${QRIS_NOBU_API_INQUIRY_URL}
      - QRIS_NOBU_DYNAMIC_PASSWORD=${QRIS_NOBU_DYNAMIC_PASSWORD}
      - QRIS_NOBU_DYNAMIC_SECRET_KEY=${QRIS_NOBU_DYNAMIC_SECRET_KEY}
      - QRIS_NOBU_DYNAMIC_USERNAME=${QRIS_NOBU_DYNAMIC_USERNAME}
      - QRIS_NOBU_STATIC_PASSWORD=${QRIS_NOBU_STATIC_PASSWORD}
      - QRIS_NOBU_STATIC_USERNAME=${QRIS_NOBU_STATIC_USERNAME}
      - SERVICE_LOGSTASH_HOST=10.6.6.26:5000
      - SERVICE_NAME=callback-service-${APPLICATION_SERVERIP}
      - SERVICE_NAME=payment-service-${APPLICATION_SERVERIP}
      - TZ=${TZ}
  payment:
    image: ${IMAGE_PAYMENT}
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/payment:/usr/apps/log
    ports:
      - 8489:8080
    depends_on:
      - postgresql
      - discovery-server
      - redis
      - datarepo
    environment:
      - APPLICATION_DATAREPO=${APPLICATION_DATAREPO}
      - APPLICATION_DEFAULT_DATAREPO=${APPLICATION_DEFAULT_DATAREPO}
      - APPLICATION_MYDATAREPO=${APPLICATION_MYDATAREPO}
      - APPLICATION_MYDATAREPOCODE=${APPLICATION_MYDATAREPOCODE}
      - APPLICATION_SERVERIP=${APPLICATION_SERVERIP}
      - DB_SSL_CONFIG=
      - ID_CO_PRISMALINK_ENV=development
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC_13=${KAFKA_TOPIC_13}
      - KAFKA_TOPIC_7=${KAFKA_TOPIC_7}
      - MBDD_CONTAINER_PAYLATER_BASEURL=http://${APPLICATION_SERVERIP}:8500
      - MBDD_CONTAINER_PROCESSOR_BASEURL=https://secure3.plink.co.id
      - MBDD_DB_CONNECTION_TIMEOUT=${MBDD_DB_CONNECTION_TIMEOUT}
      - MBDD_DB_MAX_POOL_SIZE=${MBDD_DB_MAX_POOL_SIZE}
      - MBDD_DB_MDO_DB_MDO_SCHEMA=public
      - MBDD_DB_MDO_DB_MDO=${MBDD_DB_MDO_DB_MDO}
      - MBDD_DB_MDO_HOST=${MBDD_DB_MDO_HOST}
      - MBDD_DB_MDO_PASS_MDO=${MBDD_DB_MDO_PASS_MDO}
      - MBDD_DB_MDO_PORT=${MBDD_DB_MDO_PORT}
      - MBDD_DB_MDO_USER_MDO=${MBDD_DB_MDO_USER_MDO}
      - MBDD_DB_PLINK_DB_MDO=${MBDD_DB_PLINK_DB_MDO}
      - MBDD_DB_PLINK_HOST=${MBDD_DB_PLINK_HOST}
      - MBDD_DB_PLINK_PASS_MDO=${MBDD_DB_PLINK_PASS_MDO}
      - MBDD_DB_PLINK_PORT=${MBDD_DB_PLINK_PORT}
      - MBDD_DB_PLINK_USER_MDO=${MBDD_DB_PLINK_USER_MDO}
      - MBDD_EUREKA_SERVER_HOST=discovery-server
      - MBDD_EUREKA_SERVER_PORT=8080
      - MBDD_REDIS_HOST=${MBDD_REDIS_HOST}
      - MBDD_REDIS_PASSWORD=prismalink
      - MBDD_REDIS_PORT=6379
      - MBDD_SERVER_PORT=8080
      - PLINK_LOG_SERVICE_PAYMENT=DEBUG
      - QRIS_NOBU_API_CANCELLATION_DYNAMIC_URL=${QRIS_NOBU_API_CANCELLATION_DYNAMIC_URL}
      - QRIS_NOBU_API_DYNAMIC_URL=${QRIS_NOBU_API_DYNAMIC_URL}
      - QRIS_NOBU_API_DYNAMIC_WITHOUT_TIP_URL=${QRIS_NOBU_API_DYNAMIC_WITHOUT_TIP_URL}
      - QRIS_NOBU_API_INQUIRY_URL=${QRIS_NOBU_API_INQUIRY_URL}
      - QRIS_NOBU_API_REFUND_URL=${QRIS_NOBU_API_REFUND_URL}
      - QRIS_NOBU_DYNAMIC_PASSWORD=${QRIS_NOBU_DYNAMIC_PASSWORD}
      - QRIS_NOBU_DYNAMIC_SECRET_KEY=NobuPrismalinkKey
      - QRIS_NOBU_DYNAMIC_USERNAME=${QRIS_NOBU_DYNAMIC_USERNAME}
      - QRIS_NOBU_IP_2=${QRIS_NOBU_IP_2}
      - QRIS_NOBU_STATIC_PASSWORD=${QRIS_NOBU_STATIC_PASSWORD}
      - QRIS_NOBU_STATIC_SECRET_KEY=$QRIS_NOBU_STATIC_SECRET_KEY}
      - QRIS_NOBU_STATIC_USERNAME=${QRIS_NOBU_STATIC_USERNAME}
      - REDIS_SESSION_TOKEN_KEY=${REDIS_SESSION_TOKEN_KEY}
      - REDIS_PAYMENTPAGE_SESSION_KEY=${REDIS_PAYMENTPAGE_SESSION_KEY}
      - SERVICE_LOGSTASH_HOST=10.6.6.26:5000
      - SERVICE_NAME=payment-service-${APPLICATION_SERVERIP}
      - TZ=Asia/Jakarta
      - UANGME_BASEURL=https://openapi.uangme.com/v1/
      - UANGME_PASSWORD=1fi8roqqhakq0ubuu
      - UANGME_USERNAME=prismalink
      - DOMAIN_NAME=localhost
  checkstatus:
    image: prismalinkdev/checkstatus:master-f9789f4
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/checkstatus:/usr/apps/log
    ports:
      - 8589:8080
    depends_on:
      - discovery-server
      - datarepo
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC_8=${KAFKA_TOPIC_8}
      - MBDD_EUREKA_SERVER_HOST=${MBDD_EUREKA_SERVER_HOST}
      - MBDD_EUREKA_SERVER_PORT=${MBDD_EUREKA_SERVER_PORT}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - QRIS_NOBU_API_INQUIRY_URL=${QRIS_NOBU_API_INQUIRY_URL}
      - QRIS_NOBU_DYNAMIC_PASSWORD=${QRIS_NOBU_DYNAMIC_PASSWORD}
      - QRIS_NOBU_DYNAMIC_SECRET_KEY=${QRIS_NOBU_DYNAMIC_SECRET_KEY}
      - QRIS_NOBU_DYNAMIC_USERNAME=${QRIS_NOBU_DYNAMIC_USERNAME}
      - SERVICE_LOGSTASH_HOST=10.6.6.26:5000
      - SERVICE_NAME=checkstatus-service-${APPLICATION_SERVERIP}
      - TZ=${TZ}
  merchant-notification:
    image: prismalinkdev/merchant-notification:master-d1b6240
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/merchant-notification:/usr/apps/log
      - /etc/hosts:/etc/hosts
    ports:
      - 8495:8080
    depends_on:
      - discovery-server
    environment:
      - APPLICATION_DATAREPO=001:10.5.5.118-8001,002:10.5.5.118-8002,003:10.5.5.118-8003,004:10.5.5.118-8004
      - APPLICATION_DEFAULT_DATAREPO=10.5.5.118:8002
      - APPLICATION_MYDATAREPOCODE=003
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC_1=${KAFKA_TOPIC_1}
      - KAFKA_TOPIC_5=${KAFKA_TOPIC_5}
      - KAFKA_TOPIC_6=${KAFKA_TOPIC_6}
      - KAFKA_TOPIC_7=${KAFKA_TOPIC_7}
      - KAFKA_TOPIC_8=${KAFKA_TOPIC_8}
      - MBDD_EUREKA_SERVER_HOST=${MBDD_EUREKA_SERVER_HOST}
      - MBDD_EUREKA_SERVER_PORT=${MBDD_EUREKA_SERVER_PORT}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - QRIS_NOBU_API_CANCELLATION_DYNAMIC_URL=${QRIS_NOBU_API_CANCELLATION_DYNAMIC_URL}
      - QRIS_NOBU_API_DYNAMIC_URL=${QRIS_NOBU_API_DYNAMIC_URL}
      - QRIS_NOBU_API_DYNAMIC_WITHOUT_TIP_URL=${QRIS_NOBU_API_DYNAMIC_WITHOUT_TIP_URL}
      - QRIS_NOBU_API_INQUIRY_URL=${QRIS_NOBU_API_INQUIRY_URL}
      - QRIS_NOBU_API_REFUND_URL=${QRIS_NOBU_API_REFUND_URL}
      - QRIS_NOBU_DYNAMIC_PASSWORD=${QRIS_NOBU_DYNAMIC_PASSWORD}
      - QRIS_NOBU_DYNAMIC_SECRET_KEY=${QRIS_NOBU_DYNAMIC_SECRET_KEY}
      - QRIS_NOBU_DYNAMIC_USERNAME=${QRIS_NOBU_DYNAMIC_USERNAME}
      - QRIS_NOBU_IP_1=${QRIS_NOBU_IP_1}
      - QRIS_NOBU_IP_2=${QRIS_NOBU_IP_2}
      - QRIS_NOBU_STATIC_PASSWORD=${QRIS_NOBU_STATIC_PASSWORD}
      - QRIS_NOBU_STATIC_SECRET_KEY=${QRIS_NOBU_STATIC_SECRET_KEY}
      - QRIS_NOBU_STATIC_USERNAME=${QRIS_NOBU_STATIC_USERNAME}
      - SERVICE_LOGSTASH_HOST=10.6.6.26:5000
      - SERVICE_NAME=notification-service-${APPLICATION_SERVERIP}
      - TZ=${TZ}
  paymentpage:
    image: ${IMAGE_PAYMENT_PAGE}
    networks:
      - spring-cloud-network
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/logs/paymentpage:/usr/apps/log
    ports:
      - 8493:8080
    depends_on:
      - discovery-server
      - payment
      - redis
      - postgresql
    environment:
      - DOMAIN_NAME=localhost
      - APPLICATION_DATAREPO=${APPLICATION_DATAREPO}
      - APPLICATION_DEFAULT_DATAREPO=${APPLICATION_DEFAULT_DATAREPO}
      - APPLICATION_MYDATAREPO=${APPLICATION_MYDATAREPO}
      - APPLICATION_MYDATAREPOCODE=${APPLICATION_MYDATAREPOCODE}
      - BANK_MAINTENANCE=${BANK_MAINTENANCE}
      - CC_FRONTEND_CALLBACK_URL=${CC_FRONTEND_CALLBACK_URL}
      - CC_PCS_REGISTER_URL=${CC_PCS_REGISTER_URL}
      - CIMB_URL_LOGINPAGE=${CIMB_URL_LOGINPAGE}
      - CMB_LOGIN_URL_WRAPPER=${CMB_LOGIN_URL_WRAPPER}
      - DB_SSL_CONFIG=
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC_8=${KAFKA_TOPIC_8}
      - MBDD_CONTAINER_PROCESSOR_BASEURL=${MBDD_CONTAINER_PROCESSOR_BASEURL}
      - MBDD_CONTAINER_SIMULATOR_BASEURL=${MBDD_CONTAINER_SIMULATOR_BASEURL}
      - MBDD_DB_MDO_DB_MDO_SCHEMA=${MBDD_DB_MDO_DB_MDO_SCHEMA}
      - MBDD_DB_MDO_DB_MDO=${MBDD_DB_MDO_DB_MDO}
      - MBDD_DB_MDO_HOST=${MBDD_DB_MDO_HOST}
      - MBDD_DB_MDO_PASS_MDO=${MBDD_DB_MDO_PASS_MDO}
      - MBDD_DB_MDO_PORT=${MBDD_DB_MDO_PORT}
      - MBDD_DB_MDO_USER_MDO=${MBDD_DB_MDO_USER_MDO}
      - MBDD_DB_PLINK_DB_MDO=${MBDD_DB_PLINK_DB_MDO}
      - MBDD_DB_PLINK_HOST=${MBDD_DB_PLINK_HOST}
      - MBDD_DB_PLINK_PASS_MDO=${MBDD_DB_PLINK_PASS_MDO}
      - MBDD_DB_PLINK_PORT=${MBDD_DB_PLINK_PORT}
      - MBDD_DB_PLINK_USER_MDO=${MBDD_DB_PLINK_USER_MDO}
      - MBDD_DB_PLINKCC_DB_SCHEMA=${MBDD_DB_PLINKCC_DB_SCHEMA}
      - MBDD_DB_PLINKCC_DB=${MBDD_DB_PLINKCC_DB}
      - MBDD_DB_PLINKCC_HOST=${MBDD_DB_PLINKCC_HOST}
      - MBDD_DB_PLINKCC_PASSWORD=${MBDD_DB_PLINKCC_PASSWORD}
      - MBDD_DB_PLINKCC_PORT=${MBDD_DB_PLINKCC_PORT}
      - MBDD_DB_PLINKCC_USER=${MBDD_DB_PLINKCC_USER}
      - MBDD_EUREKA_SERVER_HOST=${MBDD_EUREKA_SERVER_HOST}
      - MBDD_EUREKA_SERVER_PORT=${MBDD_EUREKA_SERVER_PORT}
      - MBDD_REDIS_HOST=${MBDD_REDIS_HOST}
      - MBDD_REDIS_PASSWORD=${MBDD_REDIS_PASSWORD}
      - MBDD_REDIS_PORT=${MBDD_REDIS_PORT}
      - MBDD_SERVER_PORT=${MBDD_SERVER_PORT}
      - PLINK_LOG_SERVICE_PAYMENTPAGE=${PLINK_LOG_SERVICE_PAYMENTPAGE}
      - PLINK_TRANSACTIONINQUIRY_URL=${PLINK_TRANSACTIONINQUIRY_URL}
      - PROFILE=${PROFILE}
      - QRIS_NOBU_API_CANCELLATION_DYNAMIC_URL=${QRIS_NOBU_API_CANCELLATION_DYNAMIC_URL}
      - QRIS_NOBU_API_DYNAMIC_URL=${QRIS_NOBU_API_DYNAMIC_URL}
      - QRIS_NOBU_API_DYNAMIC_WITHOUT_TIP_URL=${QRIS_NOBU_API_DYNAMIC_WITHOUT_TIP_URL}
      - QRIS_NOBU_API_INQUIRY_URL=${QRIS_NOBU_API_INQUIRY_URL}
      - QRIS_NOBU_API_REFUND_URL=${QRIS_NOBU_API_REFUND_URL}
      - QRIS_NOBU_DYNAMIC_PASSWORD=${QRIS_NOBU_DYNAMIC_PASSWORD}
      - QRIS_NOBU_DYNAMIC_SECRET_KEY=${QRIS_NOBU_DYNAMIC_SECRET_KEY}
      - QRIS_NOBU_DYNAMIC_USERNAME=${QRIS_NOBU_DYNAMIC_USERNAME}
      - QRIS_NOBU_IP_1=${QRIS_NOBU_IP_1}
      - QRIS_NOBU_IP_2=${QRIS_NOBU_IP_2}
      - QRIS_NOBU_STATIC_PASSWORD=${QRIS_NOBU_STATIC_PASSWORD}
      - QRIS_NOBU_STATIC_SECRET_KEY=${QRIS_NOBU_STATIC_SECRET_KEY}
      - QRIS_NOBU_STATIC_USERNAME=${QRIS_NOBU_STATIC_USERNAME}
      - REDIS_SESSION_TOKEN_KEY=${REDIS_SESSION_TOKEN_KEY}
      - REDIS_PAYMENTPAGE_SESSION_KEY=${REDIS_PAYMENTPAGE_SESSION_KEY}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SUBMIT_TRXCD=${SUBMIT_TRXCD}
      - TZ=${TZ}
      - URL_ENV=https://secure5.plink.co.id
      - URL_SUBMITTRX=${URL_SUBMITTRX}
      - VAM_BASE_URL=${VAM_BASE_URL}
networks:
  spring-cloud-network:
    driver: overlay
    attachable: true