# orkestrate 2 java projects and 1 db server
# docker-compose.yml
version: '3.8'
name: local_plink_development
services:
  db:
    image: postgres
    #running every docker start
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
       - /Users/rayakurayasem/Dejo/my-workspace/database/postgresql/data:/var/lib/postgresql/data
       - /Users/rayakurayasem/Dejo/my-workspace/database/postgresql/backups:/var/backups
  datarepo:
    image: datarepo
    restart: always
    env_file:
      - ../envs/env-datarepo
    ports:
      - '127.0.0.1:8080:8080'
  discovery:
    image: discovery
    restart: always
    ports:
      - '127.0.0.1:8681:8681'
