# orkestrate 2 java projects
version: '3.8'
name: local_plink_development
services:
  discovery:
    image: discovery
    restart: always
    env_file:
      - ../envs/snap_discovery.environment
    network_mode: host
    ports:
      - '127.0.0.1:8485:8080'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/log/discovery:/usr/apps/log

  datarepo:
    image: datarepo
    restart: always
    env_file:
      - ../envs/snap_datarepo.environment
    network_mode: host
    ports:
      - '127.0.0.1:8490:8080'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/log/datarepo:/usr/apps/log
  payment:
    image: payment
    restart: always
    env_file:
      - ../envs/snap_payment.environment
    network_mode: host
    ports:
      - '127.0.0.1:8081:8080'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/log/datarepo:/usr/apps/log