version: '3.8'
name: local_plink_development
services:
  discovery:
    image: discovery
    restart: always
    env_file:
      - ../envs/snap_discovery.environment
    network_mode: bridge
    ports:
      - '127.0.0.1:8485:8485'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/log/discovery:/usr/apps/log

  datarepo:
    image: datarepo
    restart: always
    env_file:
      - ../envs/snap_datarepo.environment
    network_mode: bridge
    ports:
      - '127.0.0.1:8490:8581'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/log/datarepo:/usr/apps/log
    links:
      - db
      - discovery
      - redis

  # payment:
  #   image: payment
  #   restart: always
  #   env_file:
  #     - ../envs/snap_payment.environment
  #   network_mode: bridge
  #   ports:
  #     - '127.0.0.1:8081:8080'
  #   volumes:
  #     - ${PERSIST_STORAGE_PATH_URL}/log/datarepo:/usr/apps/log
  #   links:
  #     - db
  #     - discovery
  #     - redis
  #     - datarepo

  redis:
    image: redis
    network_mode: bridge
    command: redis-server --requirepass prismalink
    restart: always
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/redis:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=prismalink'
    ports:
      - '127.0.0.1:8083:6379'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
      PGPORT: 5433
    network_mode: bridge
    ports:
      - '127.0.0.1:5433:5433'
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/postgresql/data:/var/lib/postgresql/data
      - ${PERSIST_STORAGE_PATH_URL}/postgresql/backups:/var/backups
