# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres
    #running every docker start
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
    network_mode: bridge
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
       - ${PERSIST_STORAGE_PATH_URL}/postgresql/data:/var/lib/postgresql/data
       - ${PERSIST_STORAGE_PATH_URL}/postgresql/backups:/var/backups

       