# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres
    #running every docker start
    restart: always
    environment:
      POSTGRES_USER: deyo
      POSTGRES_PASSWORD: root123#
    ports:
      - '5432:5432'
    volumes:
       - /d/13. Dev Local/persistance_data/postgresql/data:/var/lib/postgresql/data
       - /d/13. Dev Local/persistance_data/postgresql/backups:/var/backups

       