# docker-compose.yml
version: '3.8'
# name: redis_only
services:
   redis:
    image: redis
    #with command
    network_mode: bridge
    command: redis-server --requirepass prismalink
    restart: always
    volumes:
      - ${PERSIST_STORAGE_PATH_URL}/redis:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=prismalink'
    ports:
      - '127.0.0.1:8083:6379'


      